name: Build and Export Docker Image

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 也可以手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t PopDownloader:latest .

      - name: Export Docker Image
        run: |
          docker save PopDownloader:latest > PopDownloader-latest.tar

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PopDownloader-latest.tar
          path: PopDownloader-latest.tar
